# Generated by Django 3.2.8 on 2022-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('is_replied', models.BooleanField(default=False)),
            ],
        ),
    ]
